// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SGRB.Infrastructure.Data;
using System;

namespace SGRB.Infrastructure.Migrations
{
    [DbContext(typeof(RBasalContext))]
    partial class RBasalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGRB.AppplicationCore.Entity.Pesquisador", b =>
                {
                    b.Property<int>("PesquisadorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("InstituicaoDeEnsino");

                    b.Property<string>("Nome");

                    b.HasKey("PesquisadorId");

                    b.ToTable("Pesquisador");
                });
#pragma warning restore 612, 618
        }
    }
}
